const TOPIC = {
  BUILD_CARD: 'BUILD_CARD',
  BUILD_PLAYER: 'BUILD_PLAYER',
  SHOW_PLAYER_FORM: 'SHOW_PLAYER_FORM',
  HIDE_PLAYER_FORM: 'HIDE_PLAYER_FORM',
  SUBMIT_PLAYER_FORM: 'SUBMIT_PLAYER_FORM',
  CREATE_PLAYER_DISPLAY: 'CREATE_PLAYER_DISPLAY',
  START_GAME: 'START_GAME',
  SHOW_RULES: 'SHOW_RULES',
  SHOW_ICON_CHOICES: 'SHOW_ICON_CHOICES',
  SEND_LOG: 'SEND_LOG',
  HIGHLIGHT_PLAYER_TURN: 'HIGHLIGHT_PLAYER_TURN',
  UPDATE_FINISH_LINE: 'UPDATE_FINISH_LINE',
  WON_THE_GAME: 'WON_THE_GAME',
  FLIP_IMAGE: 'FLIP_IMAGE'
}

export default TOPIC
