const TOPIC = {
  BUILD_CARD: 'BUILD_CARD',
  BUILD_FLIPPABLE_CARD: 'BUILD_FLIPPABLE_CARD',
  BUILD_PLAYER: 'BUILD_PLAYER',
  SUBMIT_PLAYER_FORM: 'SUBMIT_PLAYER_FORM',
  START_GAME: 'START_GAME',
  SHOW_RULES: 'SHOW_RULES',
  SHOW_ICON_CHOICES: 'SHOW_ICON_CHOICES'
}

export default TOPIC;